### PR TITLE
Fix for "TypeError: Cannot read property 'hasOwnProperty' of null"

### PR DESCRIPTION
**Pull request by dex4er**
This module breaks with the message:

```
[WTF Node?] open handles:
TypeError: Cannot read property 'hasOwnProperty' of null
    at /Users/dexter/node_modules/wtfnode/index.js:315:19
    at Array.forEach (<anonymous>)
    at Object.dump (/Users/dexter/node_modules/wtfnode/index.js:304:33)
    at run.catch (/Users/dexter/hello-world.js:42:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

### CODE REVIEW

**Comment by myndzi** [comment]
Thanks for the report! Weird that Node now may return `null` in `_getActiveHandles`.

Would you mind changing this to instead take the form:
```js
  if (!h) { return; }
```
between lines 304 and 305, so that it's a bit more failure-proof?

**Comment by dex4er** [comment]
Try this one. It is really weird that handler was just `null` but what can I do? 😄 Better safe than sorry.

**Comment by myndzi** [comment]
Thanks. Sorry for making you jump through hoops, but I've had this habit of closing PRs to make slightly different choices, and it occurred to me that this is a bit unfair since it won't log contributions the same way :)

**Comment by myndzi** [comment]
Published 0.5.5

**Pull request merged**
