### PR TITLE
Show IPC socket path for servers

### LINKED ISSUE #35: IPC-socket listeners are shown as "undefined:undefined"
Not really critical since the line number is shown, and it's pretty easy to deduce that a "TCP Server" with no host or port would be an IPC socket.

Also, thanks so much for creating a zero-dependency module that tells me exactly why my process won't exit cleanly. You've probably saved me few years of my life-span.

### PR DESCRIPTION
**Pull request by ARitz-Cracker**
Fixes #35 
This was a lot easier than I thought it would be!

### CODE REVIEW

**Comment by krisreeves-stripe** [comment]
(not at home, can't look right now)

The PR says "show IPC socket path", but the code suggests you're just removing ip/port -- is there more information we can supply? Is there a way to identify explicitly that the socket is an IPC socket and set `type` accordingly?

Thanks for the PR, and I'm glad the module has helped you :)

**Comment by ARitz-Cracker** [comment]
From the NodeJS documentation:
> For a server listening on a pipe or Unix domain socket, the name is returned as a string.

So this PR detects if the returned address is a string instead of a structured object, and if it is, use that string instead of attempting to get 2 properties from that value.

**Comment by myndzi** [comment]
Hey there, sorry for the delay. I haven't used IPC sockets before, and I expected to see something by adding e.g. `net.createServer().listen('/tmp/foo');` to `kitchensink.js` a la [the docs](https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections). However, I don't. How can I reproduce a blocking / open handle for an IPC socket?

**Comment by ARitz-Cracker** [comment]
I'm sorry, but I don't know what you're saying. Here's what this PR will do given the code below.
Without the PR:
```
aritz@smallthink-vm:/tmp$ cat asdf.js
const wtf = require('wtfnode');
const net = require("net");
net.createServer().listen('/tmp/foo', () => {
        wtf.dump()
});
aritz@smallthink-vm:/tmp$ node asdf.js
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
- Servers:
  - undefined:undefined (TCP)
```
With the PR
```
aritz@smallthink-vm:/tmp$ node asdf.js
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
- Servers:
  - /tmp/foo (TCP)
```

An IPC socket server is interacted with just any other Net socket server. Only difference is that a local path is specified.

**Comment by myndzi** [comment]
You gave me what I was looking for. I don't know why, but when I tested initially, it wasn't showing anything. I was just adding it to the checklist of "manual tests" to verify.

**Comment by ARitz-Cracker** [comment]
Ah, okay! Glad I could help clarify things!

**Comment by myndzi** [comment]
Published. Thanks again for your contribution!

**Comment by ARitz-Cracker** [comment]
Thank you! 😄

**Pull request merged**
